apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-demo-2
  name: busybox-demo-2
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox-demo-2
  - name: nginx-demo-2
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: application
            operator: In
            values:
            - cipg
            - olbb
