apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy-box-demo
  name: busy-box-demo
spec:
  containers:
  - image: busybox
    name: busy-box-demo
    command:
    - sh
    - -c
    - sleep 3600
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "env"
            operator: "In"
            values: 
            - "dev"
