apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-toleration
  name: nginx-toleration
spec:
  containers:
  - image: nginx
    name: nginx-toleration
  - image: busybox
    name: busybox-toleration
    command:
    - sh
    - -c 
    - sleep 3600
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "cipg"
    effect: "NoSchedule"
