apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-resource-request
  labels:
    name: deployment-resource-request
  namespace: teknas-namespace
spec:
  replicas: 10
  selector:
    matchLabels:
      name: pod-resource-request
  template:
    metadata:
      name: pod-resource-request
      labels:
        name: pod-resource-request
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - sh
        - -c
        - sleep 3600
        resources:
          requests:
            cpu: 0.1
            memory: "100Mi"
