apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  labels:
    name: limit-range
  namespace: teknas-namespace
spec:
  limits:
  - default:
      cpu: 0.5
    defaultRequest:
      cpu: 0.1
    type: Container
